import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/shared/navbar";
import { NextUIProvider } from "@nextui-org/react";
import { ScrollProvider } from "@/utils/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Travelingo",
  description: "Generated by create next app",
};

const poppins_bold = localFont({
  src: "./Poppins-Bold.ttf",
  variable: "--font-poppins-bold",
});

const poppins_medium = localFont({
  src: "./Poppins-Medium.ttf",
  variable: "--font-poppins-medium",
});

const poppins_light = localFont({
  src: "./Poppins-Light.ttf",
  variable: "--font-poppins-light",
});

const poppins_regular = localFont({
  src: "./Poppins-Regular.ttf",
  variable: "--font-poppins-regular",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${inter.className} ${poppins_bold.variable} ${poppins_medium.variable} ${poppins_light.variable}  ${poppins_regular.variable}`}
      >
        <ScrollProvider>
         <Navbar />
          <NextUIProvider>{children}</NextUIProvider>
        </ScrollProvider>
      </body>
    </html>
  );
}
